[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "734b875a619185f09158a50b01505e8f2c7fb0f8"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "c0a156d59b5a859e384eb4e2cb666b2ba71f56792d0c1e8661874ac06a19946e"
    url = "https://github.com/grasph/WrapIt_jll/releases/download/WrapIt-v1.4.0+2/WrapIt.v1.4.0.x86_64-linux-musl.tar.gz"
[[WrapIt]]
arch = "aarch64"
git-tree-sha1 = "2488c2d2c8e6bb8ee0f441e5ab52972f98f3e348"
os = "macos"

    [[WrapIt.download]]
    sha256 = "b2c9a77f9e5cf39d37deab8979abb20ff343f19cb6fcc73bc5bd2eb1606d45be"
    url = "https://github.com/grasph/WrapIt_jll/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.aarch64-apple-darwin.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "759adc0080d11a23e0a1aebafb2ece28e57951bf"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "d65ab9a2d8787dbb318cd9679b67693322c772977b753e11164ab3ead6c7ea43"
    url = "https://github.com/grasph/WrapIt_jll/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.x86_64-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0528890414ce1229f13d87cf8cfea89f4962a83e"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "5f1e93f808c937702f9268a64aa06d8aafa94fd481f30020ef4fc87fb25d5979"
    url = "https://github.com/grasph/WrapIt_jll/releases/download/WrapIt-v1.5.0+0/WrapIt.v1.5.0.x86_64-linux-musl-cxx11.tar.gz"
