[[WrapIt]]
arch = "x86_64"
git-tree-sha1 = "734b875a619185f09158a50b01505e8f2c7fb0f8"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "c0a156d59b5a859e384eb4e2cb666b2ba71f56792d0c1e8661874ac06a19946e"
    url = "https://github.com/grasph/WrapIt_jll/releases/download/WrapIt-v1.4.0+2/WrapIt.v1.4.0.x86_64-linux-musl.tar.gz"
[[WrapIt]]
arch = "aarch64"
git-tree-sha1 = "15cb5371237788ecd6030aa7760c880d77ed30af"
os = "macos"

    [[WrapIt.download]]
    sha256 = "4cbdc46b6fd3fb41b446220538b38095a45ebadfe91edad99b8483da86778210"
    url = "https://github.com/grasph/WrapIt_jll/releases/download/WrapIt-v1.5.0+1/WrapIt.v1.5.0.aarch64-apple-darwin.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bcab3e2c8fe9edbc426caa74e191f350e69f136"
libc = "glibc"
os = "linux"

    [[WrapIt.download]]
    sha256 = "319d155f49634b44a9eec3cf768342b3e0b5b518e4bdc9e32193bc1ebc772016"
    url = "https://github.com/grasph/WrapIt_jll/releases/download/WrapIt-v1.5.0+1/WrapIt.v1.5.0.x86_64-linux-gnu-cxx11.tar.gz"
[[WrapIt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "271d98600621bad0683a498a03050dfe0d18e1e1"
libc = "musl"
os = "linux"

    [[WrapIt.download]]
    sha256 = "448ca592b89e36cea8eea5c2b085fe14f19808673f9ebb49eac90b1a94fc07fd"
    url = "https://github.com/grasph/WrapIt_jll/releases/download/WrapIt-v1.5.0+1/WrapIt.v1.5.0.x86_64-linux-musl-cxx11.tar.gz"
